# Generated by Django 5.0.1 on 2024-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='foods')),
                ('Food_sponser', models.CharField(max_length=200)),
            ],
        ),
    ]
