# Generated by Django 5.0.1 on 2024-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
