# Generated by Django 5.0.1 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_staff', '0002_foodlist_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='Food_sponser',
            new_name='Food_price',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
