# Generated by Django 5.0.1 on 2024-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_staff', '0003_rename_food_sponser_foodlist_food_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='Food_price',
            new_name='food_price',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='quantity_booked',
            field=models.IntegerField(default=0),
        ),
    ]
