# Generated by Django 5.0.1 on 2024-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_staff', '0004_rename_food_price_foodlist_food_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_booked', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Foodlist',
        ),
    ]
