# Generated by Django 5.0.1 on 2024-03-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_staff', '0006_fooditem_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
