# Generated by Django 5.0.3 on 2024-03-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess_user.userprofile')),
            ],
        ),
    ]
